### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by Fywqdk** [jlvcm/ha-actualbudget#11]
I just reinstalled the integration last night after not having had the time to play around with it for a week or two. It went up fine (though it picked up the amounts budgeted, not the amounts left after spending, which makes it a bit useless for monitoring status). However after a short while, about an hour or so, I started getting the following error on all accounts and budget categories:

```
2024-11-12 11:26:55.845 ERROR (MainThread) [custom_components.actualbudget.sensor] Unknown error updating data from ActualBudget API to budget <<Category or account>> [Errno 28] No space left on device
Traceback (most recent call last):
  File "/config/custom_components/actualbudget/sensor.py", line 300, in async_update
    budget = await api.get_budget(self._name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/actualbudget/actualbudget.py", line 117, in get_budget
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/actualbudget/actualbudget.py", line 126, in get_budget_sync
    with Actual(
  File "/usr/local/lib/python3.12/site-packages/actual/__init__.py", line 103, in __enter__
    self.download_budget(self._encryption_password)
  File "/usr/local/lib/python3.12/site-packages/actual/__init__.py", line 349, in download_budget
    self.import_zip(io.BytesIO(file_bytes))
  File "/usr/local/lib/python3.12/site-packages/actual/__init__.py", line 370, in import_zip
    zip_file.extractall(self._data_dir)
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1744, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1802, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/local/lib/python3.12/shutil.py", line 204, in copyfileobj
    fdst_write(buf)
OSError: [Errno 28] No space left on device

```

Home assistant is running on a stand alone PC as a "Generic x86-64" installation. Currently HA reports 9% disk space used (100gb free), so I am puzzled about what the problem is. Oh and Actual is running in a docker container on my Synology NAS with 75% free space overall (around 3tb free) so I can't see what how it gets to this problem. I am guessing it is something else during import of data, which somehow ends up blocking? Is it some buffer/RAM issue that it can't offload the data fast enough before more is fetched from the Actual Server? This is way above my python-for-everyday-needs skill level.

**Comment by Fywqdk** [comment]
Hmmm - This might be a HA issue. Googling around I found multiple others with similar problems when logs become too big and are compressed, but apparently not deleted.

**Comment by Fywqdk** [comment]
Reinstalled integrations, seems to run again for now.
