### ISSUE TITLE
Only Accounts seem to load

### ISSUE THREAD

**Issue by s1mpleman** [jlvcm/ha-actualbudget#8]
Just noticed this was different than when I tried originally. 

Currently I get my 3 bank accounts loaded and that's it. The only error I seemed to have is the one below. 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/actualbudget/sensor.py", line 81, in async_setup_entry
    budgets = await api.get_budgets()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/actualbudget/actualbudget.py", line 89, in get_budgets
    return await self.hass.async_add_executor_job(self.get_budgets_sync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/actualbudget/actualbudget.py", line 102, in get_budgets_sync
    category = str(budget_raw.category_item.name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ZeroBudgets' object has no attribute 'category_item'. Did you mean: 'category_id'?
```

**Comment by jlvcm** [comment]
changed to see if it fixes for you, if it doesn't, let me know and later today if i have time i'll debug and test correctly

sorry 🙏

**Comment by s1mpleman** [comment]
Absolutely nothing to be sorry about! 

```
Unknown error updating data from ActualBudget API to budget Treats. get_budget() missing 1 required positional argument: 'category'
Unknown error updating data from ActualBudget API to budget Water. get_budget() missing 1 required positional argument: 'category'
Unknown error updating data from ActualBudget API to budget Council Tax. get_budget() missing 1 required positional argument: 'category'
Unknown error updating data from ActualBudget API to budget Electricity and Gas. get_budget() missing 1 required positional argument: 'category'
Unknown error updating data from ActualBudget API to budget Baby Items. get_budget() missing 1 required positional argument: 'category'
Traceback (most recent call last):
  File "/config/custom_components/actualbudget/sensor.py", line 276, in async_update
    budget = await api.get_budget(self._name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/actualbudget/actualbudget.py", line 117, in get_budget
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/actualbudget/actualbudget.py", line 133, in get_budget_sync
    budgets_raw = get_budget(actual.session, budget_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_budget() missing 1 required positional argument: 'category'
```
Close but no cigar! They have loaded now, but are all unavailable. 

No worries, thank you for trying!

**Comment by jlvcm** [comment]
Hey hey @s1mpleman , I've tested a bit better and made some changes, let me know if the lates version fixes it for you 🙏

**Comment by Fywqdk** [comment]
Just set up this integration. At first only accounts loaded, but slowly it is picking up all the budget categories too (emojis in titles and everything)

**Comment by jlvcm** [comment]
Yeah, it's not very fast, especially with budgets, I'm getting all the historical data and updating it every time, there are some improvements to be made for sure, but let me know if it ends up working and the data is correct

**Comment by Fywqdk** [comment]
Will do. And thanks for the work here. I would offer to contribute but my abilities in python, yaml and home assistant in general are limited. Maybe one day when the kids are not a second full time job.
